spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml   #mybatis配置文件所在路径
  type-aliases-package: com.huran.entities.Dept   #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper 映射文件  

spring:
  profiles: dev
  application:
    name: mscloud-config-dept-client    #对外暴露的微服务的实列名 非常重要
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.85.10:3306/hugege?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver   #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true  #访问路径可以显示ip地址
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml   #mybatis配置文件所在路径
  type-aliases-package: com.huran.entities.Dept   #所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper 映射文件  

spring:
  profiles: test
  application:
    name: mscloud-config-dept-client    #对外暴露的微服务的实列名 非常重要
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.85.10:3306/hugege?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver   #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true  #访问路径可以显示ip地址